version: "3.9"

services:
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shortener  # ✅ Create this database at startup
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: fastapi-app
    command: ["./start.sh"]
    ports:
      - "8000:8000"
    depends_on:
      postgres-db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres-db
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres-db:5432/shortener  # ✅ Correct connection string

volumes:
  postgres_data:
